cms/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('cms.views',
    url(r'^$', 'template_list', name='template_list'),
    url(r'^list/$', 'template_list', name='template_list'),
    url(r'^list/(?P<type>\d)/$', 'template_list', name='template_list'),
    url(r'^edit/template/(?P<key>\w+)/$', 'edit_template', name='edit_template'),
)

personality/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('personality.views',
    url(r'^me/$', 'my_wine_personality', name='my_wine_personality'),
    url(r'^check/personality/exists/$', 'check_personality_exists', name='check_personality_exists'),
    url(r'^details/(?P<user_id>\d+)/(?P<order_id>[\-\w]+)/$', 'personality_details', name="personality_details"),
    url(r'^pre/questionnaire/general/$', 'pre_questionnaire_general', name='pre_questionnaire_general'),
    url(r'^pre/questionnaire/general/(?P<rsvp_code>[\-\w]{36})/$', 'pre_questionnaire_general', name='pre_questionnaire_general'),
    url(r'^pre/questionnaire/wine/$', 'pre_questionnaire_wine', name='pre_questionnaire_wine'),
    url(r'^pre/questionnaire/wine/(?P<rsvp_code>[\-\w]{36})/$', 'pre_questionnaire_wine', name='pre_questionnaire_wine'),
    url(r'^ratings/record/$', 'record_wine_ratings', name='record_wine_ratings'),
    # url(r'^ratings/record/all/$', 'record_all_wine_ratings', name='record_all_wine_ratings'),
    # url(r'^ratings/record/all/(?P<email>[@\w\+\-\.]+)/$', 'record_all_wine_ratings', name='record_all_wine_ratings'),
    url(r'^ratings/record/all/(?P<email>.+)/(?P<party_id>\d+)/$', 'record_all_wine_ratings', name='record_all_wine_ratings'),
    url(r'^ratings/info/(?P<email>.+)/(?P<party_id>\d+)/$', 'personality_rating_info', name='personality_rating_info'),
    url(r'^taster/list/(?P<taster>.+)/(?P<party_id>\d+)/$', 'taster_list', name='taster_list'),
    url(r'^member/ratings/(?P<wine_id>\d+)/$', 'member_rate_wines', name='member_rate_wines'),
    url(r'^member/ratings/overview/$', 'member_ratings_overview', name='member_ratings_overview'),
    url(r'^member/reveal/personality/$', 'member_reveal_personality', name='member_reveal_personality'),
    url(r'^ratings/overview/$', 'general_ratings_overview', name='general_ratings_overview'),
    # url(r'^ratings/(?P<selected_wine_id>\d+)/$', 'general_rate_wines', name='general_rate_wines'),
    url(r'^ratings/(?P<selected_wine_id>\d+)/$', 'general_rate_wine', name='general_rate_wine'),
)

winedora/urls.py
from django.conf.urls import patterns, include, url
# from emailusernames.forms import EmailAuthenticationForm
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'winedora.views.home', name='home'),
    # url(r'^winedora/', include('winedora.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin_tools/', include('admin_tools.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'winedora.views.home', name='landing_page'),
    url(r'^pinterest-868f3.html$', 'winedora.views.pinterest'),
    url(r'^', include('main.urls')),
    url(r'^personality/', include('personality.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^support/', include('support.urls', namespace="support")),
    url(r'^social/', include('social.urls')),
    url(r'^cms/', include('cms.urls', namespace="cms")),
    url(r'^stripe/', include('stripecard.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^pro/', include('pro.urls', namespace="pro")),
    url(r'^coupon/', include('coupon.urls')),
    url(r'^landing/', include('landing.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

from api.tools import api
urlpatterns += patterns('',
    url(r'^api/', include(api.urls)),
    url(r'^api/spec/', include('tastypie_swagger.urls', namespace='tastypie_swagger')),
    url(r'^api/log/', include('api_logger.urls', namespace='api_logger')),
) + static('api/docs/', document_root="api_docs/_build/html/") + staticfiles_urlpatterns()

personality/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from sorl.thumbnail import ImageField

# Create your models here.


class TastingKit(models.Model):

  sku = models.CharField(max_length=32, blank=True, null=True)
  name = models.CharField(max_length=128)
  price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
  comment = models.CharField(max_length=255, blank=True, null=True)
  active = models.BooleanField(default=True)
  updated = models.DateTimeField(null=True)
  created = models.DateTimeField(null=True)

  def __unicode__(self):
    return "%s" % self.name


class Wine(models.Model):
  """
    Wine for tasting
  """
  name = models.CharField(max_length=128)
  # vintage
  year = models.IntegerField(default=0)
  sip_bits = models.TextField()
  # tasting kit wine number
  number = models.IntegerField(default=0)
  active = models.BooleanField(default=True)
  # cost per bottle
  price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
  # the date this wine is no longer used for tasting
  deactivated = models.DateTimeField(null=True, blank=True)
  is_taste_kit_wine = models.BooleanField(default=False)

  sku = models.CharField(max_length=32, blank=True, null=True)
  vinely_category = models.IntegerField(default=1)
  vinely_category2 = models.FloatField(default=1.0)
  brand = models.CharField(max_length=64, blank=True, null=True)
  varietal = models.CharField(max_length=32, blank=True, null=True)
  region = models.CharField(max_length=64, blank=True, null=True)
  alcohol = models.FloatField(default=0.0)
  residual_sugar = models.FloatField(default=0.0)
  acidity = models.FloatField(default=0.0)
  ph = models.FloatField(default=0.0)
  oak = models.FloatField(default=0.0)
  body = models.FloatField(default=0.0)
  fruit = models.FloatField(default=0.0)
  tannin = models.FloatField(default=0.0)
  supplier = models.CharField(max_length=64, blank=True, null=True)

  sparkling = models.BooleanField(default=False)

  ENCLOSURE_CHOICES = (
      (0, u'Unknown'),
      (1, u'Screw'),
      (2, u'Cork')
  )

  enclosure = models.IntegerField(choices=ENCLOSURE_CHOICES, default=ENCLOSURE_CHOICES[0][0])

  WINE_COLOR = (
      (0, u'Red'),
      (1, u'White'),
      (2, u'Ros\xc3')
  )

  color = models.IntegerField(choices=WINE_COLOR, default=WINE_COLOR[0][0])
  comment = models.CharField(max_length=255, blank=True, null=True)
  updated = models.DateTimeField(null=True)
  created = models.DateTimeField(null=True)
  image = ImageField(upload_to="wine_label/", blank=True, null=True)

  def deactivate(self):
    self.active = False
    self.deactivated = timezone.today()
    self.save()

  def activate(self):
    self.active = True
    self.save()

  # def __unicode__(self):
  #   return "%s: %s" % (self.number, self.name)

  def __unicode__(self):
    return "%s [%.1f]" % (self.name, self.vinely_category2,)

  def full_display(self):
    return "%s [%.1f, %s, %s]" % (self.name, self.vinely_category2, self.get_color_display(), "Sparkling" if self.sparkling else "Regular", )


class WineRatingData(models.Model):

  LIKENESS_CHOICES = (
      (0, 'Not Answered'),
      (1, 'Hate'),
      (2, 'Dislike'),
      (3, 'Neutral'),
      (4, 'Like'),
      (5, 'Love'),
  )

  # DNL_CHOICES = (
  #   (0, 'Not Answered'),
  #   (1, 'Dislike'),
  #   (2, 'Neutral'),
  #   (3, 'Like'),
  # )

  DNL_CHOICES = (
      (0, 'Not Answered'),
      (1, 'Too Little'),
      (2, 'Just Right'),
      (3, 'Too Much'),
  )

  SWEET_CHOICES = (
      (0, 'Not Answered'),
      (1, 'Tart'),
      (2, 'Semi Tart'),
      (3, 'Neutral'),
      (4, 'Semi Sweet'),
      (5, 'Sweet'),
  )

  WEIGHT_CHOICES = (
      (0, 'Not Answered'),
      (1, 'Light'),
      (2, 'Semi Light'),
      (3, 'Medium'),
      (4, 'Semi Heavy'),
      (5, 'Heavy'),
  )

  TEXTURE_CHOICES = (
      (0, 'Not Answered'),
      (1, 'Silky'),
      (2, 'Semi Silky'),
      (3, 'Neutral'),
      (4, 'Semi Furry'),
      (5, 'Furry'),
  )

  SIZZLE_CHOICES = (
      (0, 'Not Answered'),
      (1, 'None'),
      (2, 'Somewhat'),
      (3, 'Tingle'),
      (4, 'Semi Burn'),
      (5, 'Burn')
  )

  user = models.ForeignKey(User)
  wine = models.ForeignKey(Wine)
  overall = models.IntegerField(choices=LIKENESS_CHOICES, default=LIKENESS_CHOICES[0][0])
  dnl = models.IntegerField(choices=DNL_CHOICES, default=DNL_CHOICES[0][0])
  sweet = models.IntegerField(choices=SWEET_CHOICES, default=SWEET_CHOICES[0][0])
  sweet_dnl = models.IntegerField(choices=DNL_CHOICES, default=DNL_CHOICES[0][0])
  weight = models.IntegerField(choices=WEIGHT_CHOICES, default=WEIGHT_CHOICES[0][0])
  weight_dnl = models.IntegerField(choices=DNL_CHOICES, default=DNL_CHOICES[0][0])
  texture = models.IntegerField(choices=TEXTURE_CHOICES, default=TEXTURE_CHOICES[0][0])
  texture_dnl = models.IntegerField(choices=DNL_CHOICES, default=DNL_CHOICES[0][0])
  sizzle = models.IntegerField(choices=SIZZLE_CHOICES, default=SIZZLE_CHOICES[0][0])
  sizzle_dnl = models.IntegerField(choices=DNL_CHOICES, default=DNL_CHOICES[0][0])
  timestamp = models.DateTimeField(auto_now=True)

  class Meta:
    ordering = ['wine__number']


class WinePersonality(models.Model):
  """
    Existing wine personalities
  """

  MYSTERY = "Mystery"

  name = models.CharField(max_length=32)
  headline = models.CharField(max_length=64)
  suffix = models.CharField(max_length=16)
  description = models.TextField()

  def __unicode__(self):
    if self.name:
      return self.name
    else:
      return WinePersonality.MYSTERY


class SurveyWine(models.Model):

  name = models.CharField(max_length=32)

  COLOR_CHOICES = (
    (0, 'Red'),
    (1, 'White'),
    (2, 'Other')
  )
  color = models.IntegerField(choices=COLOR_CHOICES, default=COLOR_CHOICES[0][0])

  def __unicode__(self):
    if self.id == 13:
      # for unicode safe export via csv in support/management/commands/export_survey.py
      return "Rose"
    else:
      return self.name


class GeneralTaste(models.Model):
  """
    General taste questionnaire
  """

  user = models.ForeignKey(User)

  # question 1
  DRINK_REGULAR_CHOICES = (
      (1, 'Coffee.'),
      (2, 'Tea.'),
      (3, 'Neither.')
  )
  drink_regularly = models.IntegerField(choices=DRINK_REGULAR_CHOICES, default=0, verbose_name='What do you drink most regularly?')

  # question 2
  COFFEE_CHOICES = (
      (1, 'Bold.'),
      (2, 'Medium.'),
      (3, 'Mild.')
  )
  coffee_type = models.IntegerField(choices=COFFEE_CHOICES, default=0, verbose_name='What type of [coffee/tea] do you prefer?', blank=True, null=True)

  # question 3
  COFFEE_TAKE_CHOICES = (
      (1, 'Plain.'),
      (2, 'With cream.'),
      (3, 'With sugar.'),
      (4, 'With cream and sugar.'),
  )
  coffee_take = models.IntegerField(choices=COFFEE_TAKE_CHOICES, default=0, verbose_name='How do you typically take your [coffee/tea]?', blank=True, null=True)

  # question 4
  SALTY_FOOD_CHOICES = (
      (1, 'The more salty, the better.'),
      (2, 'I enjoy the taste, but in moderation.'),
      (3, 'If it\'s not there, I don\'t even notice.'),
      (4, 'Don\'t care for it.'),
      (5, 'Hate salt altogether.'),
      # (6, "None. I'll Drink them all"),
  )
  salty_food = models.IntegerField(choices=SALTY_FOOD_CHOICES, default=0, verbose_name='Do you enjoy salty food/snacks?', blank=True, null=True)

  # question 5
  CITRUS_CHOICES = (
      (1, 'I love lemons and limes on their own.'),
      (2, 'I prefer it with a touch of sweetness, like grapefruit juice.'),
      (3, 'On the sweeter side.  Like orange juice.'),
      (4, 'As a soda flavor.'),
      (5, 'I do not enjoy citrus, whatsoever.'),
  )
  citrus = models.IntegerField(choices=CITRUS_CHOICES, default=0, verbose_name='How do you like your citrus?')

  # question 6
  EARTHY_CHOICES = (
      (1, 'Love, love, love\'em.'),
      (2, 'I\'ll take them as an addition to a dish.'),
      (3, 'A touch will do, but that\'s it.'),
      (4, 'Not really a fan.'),
      (5, 'I\'d rather walk on them than eat them.'),
  )
  earthy = models.IntegerField(choices=EARTHY_CHOICES, default=0, verbose_name='Tell us your feelings on earthy FLAVORS like mushrooms and truffles.')

  # question 7
  BERRIES_CHOICES = (
      (1, 'I enjoy them all by themselves.'),
      (2, 'I like them in a dessert.'),
      (3, 'They\'re great.  But I\'d rather eat them as a jelly or jam.'),
      (4, 'They\'re OK.'),
      (5, 'Berries? Ick.'),
      # (6, "None. I'll Drink them all")
  )
  berries = models.IntegerField(choices=BERRIES_CHOICES, default=0, verbose_name='How do you feel about berries?')

  # question 8
  ARTIFICIAL_CHOICES = (
      (1, 'Every day, all the time.'),
      (2, 'On occasion.'),
      (3, 'I use them only if my food or drink really needs sweetening.'),
      (4, 'Rarely.'),
      (5, 'No way.')
  )
  artificial = models.IntegerField(choices=ARTIFICIAL_CHOICES, default=0, verbose_name='Do you use artificial sweeteners or consume products with sweeteners in them (i.e. diet soda)?')

  # question 9
  NEW_FLAVORS_CHOICES = (
      (1, 'All the time!'),
      (2, 'Often.'),
      (3, 'Sometimes.'),
      (4, 'Rarely.'),
      (5, 'Never.')
  )
  new_flavors = models.IntegerField(choices=NEW_FLAVORS_CHOICES, default=0, verbose_name='How often do you try out new foods and flavors?')


class WineTaste(models.Model):

  user = models.ForeignKey(User)

  # question 1
  TYPICALLY_DRINK_CHOICES = (
      (1, 'Both red and white wine.'),
      (2, 'Red wines only.'),
      (3, 'White wines only.')
  )
  typically_drink = models.IntegerField(choices=TYPICALLY_DRINK_CHOICES, default=0, verbose_name='Do you typically drink: (select one):')

  # question 2
  RED_BODY_CHOICES = (
    (1, 'Light-Medium body'),
    (2, 'Medium-Full body'),
    (3, 'No Clue/It Depends')
  )
  red_body = models.IntegerField(choices=RED_BODY_CHOICES, default=0, verbose_name='Body', blank=True, null=True)

  RED_SWEETNESS_CHOICES = (
    (1, 'Sweet'),

personality/templates/personality/member_reveal_personality.html
{% extends "winedora/base_html5.html" %}

{% load static %}

{% block header %}
  <h1 class="headline">{{ user.first_name }}, you are {{ wine_personality.name }}</h1>
{% endblock header %}

{% block content %}
<div class="container" data-spy="scroll" data-offset="50" data-target=".subnav">
  <div class="span4 offset1">
    <div class="personality-badge-detail">
      <img src="{{ STATIC_URL }}img/club_badge_{{ wine_personality.suffix }}.png">
    </div>
  </div>
  <div class="span5">
    <p class="state-head"><strong>{{ wine_personality.name }}</strong></p>
    <br />
    <p>{{ wine_personality.headline }}</p>
    <p>{{ wine_personality.description }}</p>
    <p>Congratulations! Now that wine personality has been revealed, 
      you never have to settle for a bottle of wine you don't enjoy.
    </p>
    <p>Vinely will use your taste data to deliver wines you're sure to love, right to your door each month.</p>
    <div class="vertical-space">&nbsp;</div>
    <a href="{% url home_club_member %}" class="btn btn-primary btn-large">Home</a>
    <div class="vertical-space">&nbsp;</div>
  </div>
</div>
{% endblock content %}

personality/templates/personality/personality_details.html
{% extends "winedora/base_html5.html" %}

{% block header %}
  <h1>Receiver Wine Personality</h1>
{% endblock header %}

{% block content %}

<div class="container" data-spy="scroll" data-offset="50" data-target=".subnav">

  <section id="wine_personality">
  <div class="row">
    {% if personality %}
      <div class="span12">
        {% if order %}
        <p>Order: <a href="{% url supplier_edit_order order.order_id %}">{{ order.order_id }}</a><p>

        <p><h3>Shipping Information</h3></p>
        <address>
          <p>{{ order.receiver.first_name }} {{ order.receiver.last_name }}</p>
          <p>{{ order.shipping_address.street1 }}</p>
          {% if order.shipping_address.street2 %}
          <p>{{ order.shipping_address.street2 }}</p>
          {% endif %}
          <p>{{ order.shipping_address.city }}, {{ order.shipping_address.state }} {{ order.shipping_address.zipcode }}</p>
        </address>
        {% endif %}
        <p>
        <h3>Customer is a <span class="uppercase">{{ personality.name }}</span></h3>
        </p>
      </div>
      <div class="span12">
        <p class="lead">
        {{ personality.description }}
        </p>
      </div>
    {% else %}
      <div class="span12">
        Customer has yet to discover their wine personality.
      </div>
    {% endif %}

    {% if rating_data %}
      <table class="table">
        <thead>
          <tr>
            <th>Features</th>
            <th>Wine 1</th>
            <th>Wine 2</th>
            <th>Wine 3</th>
            <th>Wine 4</th>
            <th>Wine 5</th>
            <th>Wine 6</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Overall</td>
            <td>{{ rating_data.wine1.overall }} [{{ rating_data.wine1.get_overall_display }}]</td>
            <td>{{ rating_data.wine2.overall }} [{{ rating_data.wine2.get_overall_display }}]</td>
            <td>{{ rating_data.wine3.overall }} [{{ rating_data.wine3.get_overall_display }}]</td>
            <td>{{ rating_data.wine4.overall }} [{{ rating_data.wine4.get_overall_display }}]</td>
            <td>{{ rating_data.wine5.overall }} [{{ rating_data.wine5.get_overall_display }}]</td>
            <td>{{ rating_data.wine6.overall }} [{{ rating_data.wine6.get_overall_display }}]</td>
          </tr>
          <tr>
            <td>Sweet</td>
            <td>{{ rating_data.wine1.sweet }} [{{ rating_data.wine1.get_sweet_dnl_display }}]</td>
            <td>{{ rating_data.wine2.sweet }} [{{ rating_data.wine2.get_sweet_dnl_display }}]</td>
            <td>{{ rating_data.wine3.sweet }} [{{ rating_data.wine3.get_sweet_dnl_display }}]</td>
            <td>{{ rating_data.wine4.sweet }} [{{ rating_data.wine4.get_sweet_dnl_display }}]</td>
            <td>{{ rating_data.wine5.sweet }} [{{ rating_data.wine5.get_sweet_dnl_display }}]</td>
            <td>{{ rating_data.wine6.sweet }} [{{ rating_data.wine6.get_sweet_dnl_display }}]</td>
          </tr>
          <tr>
            <td>Weight</td>
            <td>{{ rating_data.wine1.weight }} [{{ rating_data.wine1.get_weight_dnl_display }}]</td>
            <td>{{ rating_data.wine2.weight }} [{{ rating_data.wine2.get_weight_dnl_display }}]</td>
            <td>{{ rating_data.wine3.weight }} [{{ rating_data.wine3.get_weight_dnl_display }}]</td>
            <td>{{ rating_data.wine4.weight }} [{{ rating_data.wine4.get_weight_dnl_display }}]</td>
            <td>{{ rating_data.wine5.weight }} [{{ rating_data.wine5.get_weight_dnl_display }}]</td>
            <td>{{ rating_data.wine6.weight }} [{{ rating_data.wine6.get_weight_dnl_display }}]</td>
          </tr>
          <tr>
            <td>Texture</td>
            <td>{{ rating_data.wine1.texture }} [{{ rating_data.wine1.get_texture_dnl_display }}]</td>
            <td>{{ rating_data.wine2.texture }} [{{ rating_data.wine2.get_texture_dnl_display }}]</td>
            <td>{{ rating_data.wine3.texture }} [{{ rating_data.wine3.get_texture_dnl_display }}]</td>
            <td>{{ rating_data.wine4.texture }} [{{ rating_data.wine4.get_texture_dnl_display }}]</td>
            <td>{{ rating_data.wine5.texture }} [{{ rating_data.wine5.get_texture_dnl_display }}]</td>
            <td>{{ rating_data.wine6.texture }} [{{ rating_data.wine6.get_texture_dnl_display }}]</td>
          </tr>
          <tr>
            <td>Sizzle</td>
            <td>{{ rating_data.wine1.sizzle }} [{{ rating_data.wine1.get_sizzle_dnl_display }}]</td>
            <td>{{ rating_data.wine2.sizzle }} [{{ rating_data.wine2.get_sizzle_dnl_display }}]</td>
            <td>{{ rating_data.wine3.sizzle }} [{{ rating_data.wine3.get_sizzle_dnl_display }}]</td>
            <td>{{ rating_data.wine4.sizzle }} [{{ rating_data.wine4.get_sizzle_dnl_display }}]</td>
            <td>{{ rating_data.wine5.sizzle }} [{{ rating_data.wine5.get_sizzle_dnl_display }}]</td>
            <td>{{ rating_data.wine6.sizzle }} [{{ rating_data.wine6.get_sizzle_dnl_display }}]</td>
          </tr>
        </tbody>
      </table>
    {% endif %}


    </div>
  </section>

</div>

{% endblock content %}

personality/templates/personality/pre_questionnaire_general.html
{% extends "winedora/base_html5.html" %}

{% block additional_styles %}
  <style type="text/css">
    ul {
      list-style-type:none;
    }

    li {
      margin-right: 10px;
    }

    .radio {
      display: inline;
    }

    .shaded {
      background-color: #EAEAE3;
    }

    .control-label {
      font-weight: 600;
      margin-bottom: 10px;
    }

    .control-group {
      margin-bottom: 20px;
    }

    .sub-instruction {
      margin-left: 25px;
      font-size: 0.8em;
    }

  </style>
{% endblock %}

{% block header %}
  <h1>General Tastes and Preferences (Page 1 of 2)</h1>
  Please fill out the following questionnaire before coming to the party
{% endblock header %}

{% block content %}

<div class="container" data-spy="scroll" data-offset="50" data-target=".subnav">
  <section id="general-taste-questionnaire">
  <div class="row">
    <div class="span12">
      <form action="{{ app_path }}" method="POST">
        {% csrf_token %}
        {{ form.user }}
        {{ form.errors }}

        <div class="control-group{% if form.drink_regularly.errors %} error{% endif %}">
          <div class="control-label" for="id_drink_regularly">1. {{ form.drink_regularly.label }}</div>
          <div class="controls">
            {{ form.drink_regularly}} 
            {% if form.drink_regularly.errors %}
              <span class="help-inline">
                {{ form.drink_regularly.errors }}
              </span>
            {% endif %}
          </div>
          <div class="sub-instruction">
          If "Neither", skip to question 5.
          </div>
        </div>        

        <div class="control-group{% if form.coffee_type.errors %} error{% endif %}">
          <div class="control-label" for="id_coffee_type">2. {{ form.coffee_type.label }}</div>
          <div class="controls">
            {{ form.coffee_type}} 
            {% if form.coffee_type.errors %}
              <span class="help-inline">
                {{ form.coffee_type.errors }}
              </span>
            {% endif %}
          </div>
        </div>        

        <div class="control-group{% if form.coffee_take.errors %} error{% endif %}">
          <div class="control-label" for="id_coffee_take">3. {{ form.coffee_take.label }}</div>
          <div class="controls">
            {{ form.coffee_take}} 
            {% if form.coffee_take.errors %}
              <span class="help-inline">
                {{ form.coffee_take.errors }}
              </span>
            {% endif %}
          </div>
        </div>

        <div class="control-group{% if form.salty_food.errors %} error{% endif %}">
          <div class="control-label" for="id_salty_food">4. {{ form.salty_food.label }}</div>
          <div class="controls">
            {{ form.salty_food}} 
            {% if form.salty_food.errors %}
              <span class="help-inline">
                {{ form.salty_food.errors }}
              </span>
            {% endif %}
          </div>
        </div>


        <div class="control-group{% if form.citrus.errors %} error{% endif %}">
          <div class="control-label" for="id_citrus">5. {{ form.citrus.label }}</div>
          <div class="controls">
            {{ form.citrus}} 
            {% if form.citrus.errors %}
              <span class="help-inline">
                {{ form.citrus.errors }}
              </span>
            {% endif %}
          </div>
        </div>

        <div class="control-group{% if form.earthy.errors %} error{% endif %}">
          <div class="control-label" for="id_earthy">6. {{ form.earthy.label }}</div>
          <div class="controls">
            {{ form.earthy}} 
            {% if form.earthy.errors %}
              <span class="help-inline">
                {{ form.earthy.errors }}
              </span>
            {% endif %}
          </div>
        </div>        

        <div class="control-group{% if form.berries.errors %} error{% endif %}">
          <div class="control-label" for="id_berries">7. {{ form.berries.label }}</div>
          <div class="controls">
            {{ form.berries}} 
            {% if form.berries.errors %}
              <span class="help-inline">
                {{ form.berries.errors }}
              </span>
            {% endif %}
          </div>
        </div>        

        <div class="control-group{% if form.artificial.errors %} error{% endif %}">
          <div class="control-label" for="id_artificial">8. {{ form.artificial.label }}</div>
          <div class="controls">
            {{ form.artificial}} 
            {% if form.artificial.errors %}
              <span class="help-inline">
                {{ form.artificial.errors }}
              </span>
            {% endif %}
          </div>
        </div>        

        <div class="control-group{% if form.new_flavors.errors %} error{% endif %}">
          <div class="control-label" for="id_new_flavors">9. {{ form.new_flavors.label }}</div>
          <div class="controls">
            {{ form.new_flavors}} 
            {% if form.new_flavors.errors %}
              <span class="help-inline">
                {{ form.new_flavors.errors }}
              </span>
            {% endif %}
          </div>
        </div>        
        
        <div class="control-group">
          <div class="form-actions">
            <button class="btn btn-primary" type="submit">Next</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  </section>
</div>

{% endblock content %}