accounts/urls.py
from django.conf.urls import patterns, url

from accounts.forms import VinelyEmailAuthenticationForm

urlpatterns = patterns('',

  #  url(r'^login/$', 'django.contrib.auth.views.login',
  #    {'authentication_form': EmailAuthenticationForm, 'template_name': 'email_usernames/login.html'}, name='login'),
  url(r'^login/$', 'django.contrib.auth.views.login',
     {'authentication_form': VinelyEmailAuthenticationForm}, name='login'),
  # url(r'^login/$', 'accounts.views.login',
  #    {'authentication_form': VinelyEmailAuthenticationForm}, name='login'),
  url(r'^my/information/$', 'accounts.views.my_information', name='my_information'),
  url(r'^card/delete/$', 'accounts.views.delete_card', name='delete_card'),
  url(r'^edit/subscription/$', 'accounts.views.edit_subscription', name='edit_subscription'),
  url(r'^cancel/subscription/$', 'accounts.views.cancel_subscription', name='cancel_subscription'),
  url(r'^change/password/$', 'accounts.views.change_password', name='change_password'),
  url(r'^verify/eligibility/$', 'accounts.views.verify_eligibility', name='verify_eligibility'),
  url(r'^forgot/password/$', 'accounts.views.forgot_password', name='forgot_password'),
  url(r'^activate/account/$', 'accounts.views.activate_account', name='activate_account'),
  url(r'^profile/$', 'accounts.views.profile', name='accounts_profile'),
  # url(r'^signup/(?P<account_type>\d+)/$', 'accounts.views.sign_up', name='sign_up'),
  url(r'^verify/(?P<verification_code>[\-\w]{36})/$', 'accounts.views.verify_account', name='verify_account'),
  url(r'^verify/email/(?P<verification_code>[\-\w]{36})/$', 'accounts.views.verify_email', name='verify_email'),
  url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
  # url(r'^logout/$', 'accounts.views.logout', name='logout'),
  url(r'^terms/$', 'accounts.views.terms', name="terms"),
  url(r'^privacy/$', 'accounts.views.privacy', name='privacy'),
  # url(r'^make/(?P<account_type>\w+)/$', 'accounts.views.make_pro_host', name='make_pro_host'),
  url(r'^make/host/$', 'accounts.views.make_host', name='make_host'),
  url(r'^make/host/(?P<state>\w+)/$', 'accounts.views.make_host', name='make_host'),
  url(r'^make/pro/$', 'accounts.views.make_pro', name='make_pro'),
  url(r'^make/pro/(?P<state>\w+)/$', 'accounts.views.make_pro', name='make_pro'),
  url(r'^make/taster/(?P<rsvp_code>[\-\w]{36})/$', 'accounts.views.make_taster', name='make_taster'),
  url(r'^unlink/pro/$', 'accounts.views.pro_unlink', name='pro_unlink'),
  url(r'^unlink/host/$', 'accounts.views.host_unlink', name='host_unlink'),
  url(r'^link/pro/$', 'accounts.views.pro_link', name='pro_link'),

  url(r'^join/club/$', 'accounts.views.join_club_start', name='join_club_start'),
  url(r'^join/club/hi/(?P<state>\w+)/$', 'accounts.views.join_club_start', name='join_club_start'),
  url(r'^join/club/signup/$', 'accounts.views.join_club_signup', name='join_club_signup'),
  url(r'^join/club/shipping/$', 'accounts.views.join_club_shipping', name='join_club_shipping'),
  url(r'^join/club/review/$', 'accounts.views.join_club_review', name='join_club_review'),
  url(r'^join/club/done/(?P<order_id>[\-\w]+)/$', 'accounts.views.join_club_done', name='join_club_done'),

  # test
  url(r'^my/information/test/$', 'accounts.views.fix_my_picture', name='fix_my_picture'),
)

cms/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('cms.views',
    url(r'^$', 'template_list', name='template_list'),
    url(r'^list/$', 'template_list', name='template_list'),
    url(r'^list/(?P<type>\d)/$', 'template_list', name='template_list'),
    url(r'^edit/template/(?P<key>\w+)/$', 'edit_template', name='edit_template'),
)

winedora/urls.py
from django.conf.urls import patterns, include, url
# from emailusernames.forms import EmailAuthenticationForm
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'winedora.views.home', name='home'),
    # url(r'^winedora/', include('winedora.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin_tools/', include('admin_tools.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'winedora.views.home', name='landing_page'),
    url(r'^pinterest-868f3.html$', 'winedora.views.pinterest'),
    url(r'^', include('main.urls')),
    url(r'^personality/', include('personality.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^support/', include('support.urls', namespace="support")),
    url(r'^social/', include('social.urls')),
    url(r'^cms/', include('cms.urls', namespace="cms")),
    url(r'^stripe/', include('stripecard.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^pro/', include('pro.urls', namespace="pro")),
    url(r'^coupon/', include('coupon.urls')),
    url(r'^landing/', include('landing.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

from api.tools import api
urlpatterns += patterns('',
    url(r'^api/', include(api.urls)),
    url(r'^api/spec/', include('tastypie_swagger.urls', namespace='tastypie_swagger')),
    url(r'^api/log/', include('api_logger.urls', namespace='api_logger')),
) + static('api/docs/', document_root="api_docs/_build/html/") + staticfiles_urlpatterns()

accounts/models.py
from django.db import models, transaction
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.conf import settings
from Crypto.Cipher import AES
from sorl.thumbnail import ImageField

from personality.models import WinePersonality
from django.contrib.localflavor.us import models as us_models
from django.utils import timezone
from django.http import HttpRequest

from dateutil.relativedelta import relativedelta
from datetime import datetime, date, timedelta, tzinfo

from stripecard.models import StripeCard
from personality.models import WineRatingData

from pyproj import Geod
from random import randint
from decimal import Decimal

import stripe
import binascii
import string
import math

ZERO = timedelta(0)

import logging
log = logging.getLogger(__name__)


# Create your models here.

# have to redefine instead of importing from main.utils due to circular dependency
class UTC(tzinfo):
  """UTC"""

  def utcoffset(self, dt):
    return ZERO

  def tzname(self, dt):
    return "UTC"

  def dst(self, dt):
    return ZERO


class Address(models.Model):
  nick_name = models.CharField(max_length=64, null=True, blank=True)
  company_co = models.CharField(max_length=64, null=True, blank=True)
  street1 = models.CharField(verbose_name="Address 1", max_length=128)
  street2 = models.CharField(verbose_name="Address 2", max_length=128, null=True, blank=True)
  city = models.CharField(max_length=64)
  state = us_models.USStateField()
  zipcode = models.CharField(max_length=20, help_text="5 digit or extended zipcode")

  class Meta:
    verbose_name_plural = u'addresses'

  def __unicode__(self):
    return "%s, %s" % (self.street1, self.zipcode)

  def full_text(self):
    return "%s, %s, %s %s" % (self.street1, self.city, self.state, self.zipcode)

  def google_maps_address(self):
    search_str = "%s %s, %s %s" % (self.street1, self.city, self.state, self.zipcode)
    new_str = string.replace(search_str, " ", "+")
    return new_str


class CreditCard(models.Model):
  nick_name = models.CharField(max_length=64, null=True, blank=True)
  card_number = models.CharField(max_length=32)
  exp_month = models.IntegerField()
  exp_year = models.IntegerField()
  #expiry_date = models.DateField()
  verification_code = models.CharField(max_length=32)
  billing_zipcode = models.CharField(max_length=5, help_text="5 digit zipcode")
  card_type = models.CharField(max_length=32, default="Unknown")

  def last_four(self):
    cipher = AES.new(settings.SECRET_KEY[:32], AES.MODE_ECB)
    card_cipher = binascii.unhexlify(self.card_number)
    pad_number = cipher.decrypt(card_cipher)
    card_num = string.strip(pad_number, 'X')
    return card_num[-4:]

  def exp_date(self):
    return "%s/%s" % (self.exp_month, self.exp_year)

  def encrypt_card_num(self, number):
    """
      saves card number
    """
    pad_number = string.ljust(str(number), 16, 'X')
    cipher = AES.new(settings.SECRET_KEY[:32], AES.MODE_ECB)
    msg = cipher.encrypt(pad_number)
    self.card_number = msg.encode('hex')

  def decrypt_card_num(self, number=None):
    cipher = AES.new(settings.SECRET_KEY[:32], AES.MODE_ECB)
    if number:
      card_cipher = binascii.unhexlify(number)
    else:
      card_cipher = binascii.unhexlify(self.card_number)
    pad_number = cipher.decrypt(card_cipher)
    return string.strip(pad_number, 'X')

  def encrypt_cvv(self, cvv):
    """
      encrypts cvv
    """
    pad_number = string.ljust(str(cvv), 16, 'X')
    cipher = AES.new(settings.SECRET_KEY[:32], AES.MODE_ECB)
    msg = cipher.encrypt(pad_number)
    self.verification_code = msg.encode('hex')

  def decrypt_cvv(self, cvv=None):
    cipher = AES.new(settings.SECRET_KEY[:32], AES.MODE_ECB)
    if cvv:
      card_cipher = binascii.unhexlify(cvv)
    else:
      card_cipher = binascii.unhexlify(self.verification_code)
    pad_number = cipher.decrypt(card_cipher)
    return string.strip(pad_number, 'X')


class VerificationQueue(models.Model):

  VERIFICATION_CHOICES = (
    (0, 'New Account'),
    (1, 'Forgot Password'),
    (2, 'Verify E-mail')
  )

  user = models.ForeignKey(User)
  verification_code = models.CharField(max_length=64)
  verified = models.BooleanField(default=False)
  verification_type = models.IntegerField(choices=VERIFICATION_CHOICES, default=0)
  #: verify_data is used when verifying e-mail only for now
  verify_data = models.CharField(max_length=128, blank=True, null=True)
  created = models.DateTimeField(auto_now_add=True)


class UserProfile(models.Model):
  user = models.OneToOneField(User)

  vinely_customer_id = models.CharField(max_length=16, blank=True, null=True, db_index=True)

  image = ImageField(upload_to="profiles/", blank=True, null=True)
  dob = models.DateField(verbose_name="Date of Birth (mm/dd/yyyy)", null=True, blank=True)
  # drivers license number
  dl_number = models.CharField(verbose_name="Driver's Licence #", max_length=32, null=True, blank=True)
  phone = us_models.PhoneNumberField(max_length=16, null=True, blank=True)
  work_phone = us_models.PhoneNumberField(max_length=16, null=True, blank=True)
  accepted_tos = models.BooleanField(verbose_name="I accept the terms of service", default=False)
  news_optin = models.BooleanField(verbose_name="Yes, I'd like to be notified of news, offers and events at Vinely via this email address.", default=True)
  # only pro's should have mentor
  mentor = models.ForeignKey(User, null=True, blank=True, verbose_name='Vinely Pro Mentor (only for Pros)', related_name='mentees')
  current_pro = models.ForeignKey(User, null=True, blank=True, verbose_name='Current Pro (for Hosts and Tasters)', related_name='assigned_profiles')
  club_member = models.BooleanField(default=False)
  internal_pro = models.BooleanField(default=False)  # set for internal pros like training
  account_credit = models.DecimalField(max_digits=10, decimal_places=2, default=0)
  coupon = models.ForeignKey('coupon.Coupon', null=True, related_name='coupon')
  coupons = models.ManyToManyField('coupon.Coupon', null=True, related_name='coupons')

  ROLE_CHOICES = (
      (0, 'Unassigned Role'),
      (1, 'Vinely Pro'),
      (2, 'Vinely Host'),
      (3, 'Vinely Taster'),
      (4, 'Supplier'),
      (5, 'Pending Vinely Pro'),
  )
  role = models.IntegerField(choices=ROLE_CHOICES, default=ROLE_CHOICES[0][0])

  GENDER_CHOICES = (
      (0, 'FEMALE'),
      (1, 'MALE'),
      (2, 'N/A'),
  )

  gender = models.IntegerField(choices=GENDER_CHOICES, default=GENDER_CHOICES[0][0])
  zipcode = models.CharField(max_length=20, help_text="5 digit or extended zipcode of your primariy residence", null=True, blank=True)
  above_21 = models.BooleanField(verbose_name="I certify that I am over 21", default=False)

  wine_personality = models.ForeignKey(WinePersonality, default=7)
  prequestionnaire = models.BooleanField(default=False)

  # for storing default addresses
  billing_address = models.ForeignKey(Address, related_name="billed_to", null=True, blank=True)
  shipping_address = models.ForeignKey(Address, related_name="shipped_to", null=True, blank=True)
  credit_card = models.ForeignKey(CreditCard, related_name="owner", null=True, blank=True)
  stripe_card = models.ForeignKey(StripeCard, related_name="stripe_owner", null=True, blank=True)

  # for permanently storing for future
  credit_cards = models.ManyToManyField(CreditCard, related_name="owned_by", null=True, blank=True)
  stripe_cards = models.ManyToManyField(StripeCard, related_name="stripe_owned_by", null=True, blank=True)
  party_addresses = models.ManyToManyField(Address, related_name="hosting_user", null=True, blank=True)
  shipping_addresses = models.ManyToManyField(Address, related_name="shipping_user", null=True, blank=True)

  @property
  def has_parties(self):
    from main.models import PartyInvite
    return PartyInvite.objects.filter(invitee=self.user)

  @property
  def has_default_pro(self):
    from accounts.utils import get_default_pro, get_default_mentor
    if self.role == 1:
      return self.mentor == get_default_mentor()
    else:
      return self.current_pro == get_default_pro()

  def find_nearest_pro(self):
    from accounts.utils import get_default_pro, get_default_mentor
    if self.role == 1:
      default_pro = get_default_mentor()
    else:
      default_pro = get_default_pro()

    code = self.zipcode

    g = Geod(ellps='clrk66')

    if self.is_pro():
      return default_pro

    if not code:
      return default_pro

    # get all info about this zipcode
    user_zipcode = Zipcode.objects.get(code=code)

    # 1. find pro's within the same zipcode
    pros = UserProfile.objects.filter(zipcode=code, role=UserProfile.ROLE_CHOICES[1][0]).exclude(internal_pro=True)

    if pros.exists():
      # pick at random
      rand_index = randint(0, pros.count() - 1)
      # log.info('Nearest by zipcode: %s, assigned_pro: %s' % (code, pros[rand_index].user))
      return pros[rand_index].user

    # 2. if no pro within zipcode, find within state
    # NOTE: Some states are massive so limit distance
    nearby_codes = Zipcode.objects.filter(state=user_zipcode.state).values_list('code', flat=True).distinct()

    pros = UserProfile.objects.filter(zipcode__in=nearby_codes, role=UserProfile.ROLE_CHOICES[1][0])

    my_pros = {}
    if pros.exists():
      for pro in pros:
        pro_zipcode = Zipcode.objects.get(code=pro.zipcode)
        _, _, distance = g.inv(user_zipcode.longitude, user_zipcode.latitude, pro_zipcode.longitude, pro_zipcode.latitude)
        # distance returned in meters so convert to miles
        # pros should be within 25miles
        distance = distance * 0.000621371
        if distance <= 25:
          my_pros[pro.user] = distance
      # log.info('has zipcode: %s' % my_pros[pro.user])

      # TODO: how to deal with multiple pros that satisfy conditions
      # 1. if multiple active pros, find pro not assigned in last 3 months

accounts/templates/accounts/already_authenticated.html
{% extends "winedora/base_html5.html" %}

{% block header %}
{% endblock header %}

{% block content %}

<div class="container" data-spy="scroll" data-offset="50" data-target=".subnav">
    <div class="row">
      <div class="offset2 span8">
        You are currently logged in. Go back <a href="{% url home_page %}">home</a> or go to <a href="{% url my_information %}">My Account</a> to change your password.
      </div>
    </div>
    <div class="row">
      <div class="vertical-space-bottom">
        <p>&nbsp;</p>
      </div>
    </div>

</div>

{% endblock content %}

accounts/templates/accounts/host_request_sent.html
{% extends "winedora/base_html5.html" %}

{% block header %}
  <h1 class="headline">Welcome to Vinely, {{ first_name }}</h1>
{% endblock header %}

{% block content %}

<div class="container" data-spy="scroll" data-offset="50" data-target=".subnav">
  <div class="row">
    <div class="offset2 span8">
      <p>We love a good party and we're glad you'd like to host one! Stay on the lookout for an email that should be arriving from a Vinely Pro. </p>

      <p>If you haven't heard anything in 48 hours, please contact a Vinely Care Specialist at (888) 294-1128 ext. 1 or <a href="mailto:care@vinely.com">email</a> us.</p>
    </div>
  </div>
  <div class="row">
    <div class="offset2 span8">
      <p>&nbsp;</p>
    </div>
  </div>

</div>

{% endblock content %}

accounts/templates/accounts/join_club_done.html
{% extends "winedora/base_html5.html" %}

{% load static %}

{% load currency %}

{% block additional_styles %}
  <style type="text/css">
    .card-info {
      padding-top: 40px;
    }
    img.join-done {
      position: absolute;
      height: 700px;
      margin-left: -270px;
    }
    .join-club-big-name {
      position:absolute;
      margin-top: 200px;
      z-index: 200;
      margin: 210px 0;
      width: 320px;
    }
  </style>
{% endblock %}


{% block header %}
  <h1 class="headline">Congratulations!!</h1>
{% endblock header %}

{% block content %}
<div class="partycrumb main">
  <ul class="nav diy-nav">
    <li id="shipping" class="visited">&nbsp;</li>
    <li id="review" class="visited">&nbsp;</li>
    <li id="done" class="active">&nbsp;</li>
  </ul>
</div>
<div class="vertical-space">&nbsp;</div>
<div class="container" data-spy="scroll" data-offset="50" data-target=".subnav">
  <div class="row">
    <div class="span3 offset1">
      <h2><small>Shipping</small></h2>
      <address>
        <p>{{ user.first_name }} {{ user.last_name }}</p>
        <p>{{ shipping_address.street1 }}</p>
        {% if shipping_address.street2 %}
        <p>{{ shipping_address.street2 }}</p>
        {% endif %}
        <p>{{ shipping_address.city }}, {{ shipping_address.state }} {{ shipping_address.zipcode }}</p>
        <br />
        <p>Phone: {{ cart.receiver.get_profile.phone }}</p>        
      </address>

      <h2><small>Billing</small></h2>
      <p>Credit card ending in {{ credit_card.last_four }}</p>
      <p>Exp Date: {{ credit_card.exp_date }}</p>

      <h2><small>Dues</small></h2>
      {% if cart.coupon %}
        <p>Coupon: ({{ cart.coupon_amount|currency }})</p>
      {% endif %}
      <p>Subtotal: {{ cart.subtotal|currency }}</p>
      <p>Tax: {{ cart.tax|currency }}</p>
      <p><b>Total: {{ cart.total|currency }}/month</b></p>
    </div>
    <div class="span8">
      <h1 class="headline join-club-big-name">{{ user.first_name|truncatechars:15 }}</h1>
      <img class="join-done" src="{{ STATIC_URL }}img/join_club_done.png">
    </div>
  </div>
  <div class="vertical-space-bottom">&nbsp;</div>
  <div class="vertical-space-bottom">&nbsp;</div>
  <div class="vertical-space">&nbsp;</div>
  <div class="center">
    <a href="{% url home_club_member %}" class="btn btn-success btn-large">Home</a>
  </div> 
  <div class="vertical-space">&nbsp;</div>
</div>

{% endblock %}

{% block additional_scripts %}
{% endblock additional_scripts %}

accounts/templates/accounts/sign_up.html
{% extends "winedora/base_html5.html" %}

{% block header %}
  {% if already_signed_up %}
    <h1>You are already signed up!</h1>
  {% else %}
    {% if account_type == 3 %}
      {# taster #}
      <h1>Sign up to attend a future Vinely party</h1>
    {% elif account_type == 5 %}
      {# interested in tasting kit #}
      <h1>Order your own Vinely tasting kit</h1>
    {% else %}
      <h1>Become a {{ role }}</h1>
    {% endif %}
  {% endif %}
{% endblock header %}

{% block content %}

<div class="container" data-spy="scroll" data-offset="50" data-target=".subnav">
  {% if already_signed_up and not make_host_or_pro %}

    <div class="row">
      <div class="offset2 span8">
        <!-- Thank you for being an active member of Vinely. Hope you are having a blast with Vinely! -->
        Questions? Contact us at <a href="mailto:care@vinely.com">care@vinely.com</a> or 888-294-1128
      </div>
    </div>
    <div class="vertical-space">
    </div>
  {% else %}
    <div class="row">
      <div class="span8">
      <!-- It's easy to get started with Vinely! -->
      Questions? Contact us at <a href="mailto:care@vinely.com">care@vinely.com</a> or 888-294-1128
      <p>&nbsp;</p>
      </div>
    </div>
    <div class="row">
      <form class="form-horizontal well" method="POST" action="{{ app_path }}">
        {% csrf_token %}

        {% if error %}
          <div class="alert alert-error">
            {{ error }}
          </div>
        {% endif %}
        {% if form.errors %}
          <div class="alert alert-error">
            {{ form.errors }}
          </div>
        {% endif %}

        <fieldset>
          <div class="control-group">
            <div class="control-label" for="id_first_name">
            {{ form.first_name.label }}
            </div>
            <div class="controls">
              {{ form.first_name }}
            </div>
          </div>
          <div class="control-group">
            <div class="control-label" for="id_last_name">
            {{ form.last_name.label_tag }}
            </div>
            <div class="controls">
              {{ form.last_name }}
            </div>
          </div>
          <div class="control-group">
            <div class="control-label" for="id_email">
            {{ form.email.label_tag }}
            </div>
            <div class="controls">
              {{ form.email }}
            </div>
          </div>
          <div class="control-group">
            <div class="control-label" for="id_zipcode">
            {{ form.zipcode.label_tag }}
            </div>
            <div class="controls">
              {{ form.zipcode }}
            </div>
          </div>
          <div class="control-group">
            <div class="control-label" for="id_phone_number">
            {{ form.phone_number.label_tag }}
            </div>
            <div class="controls">
              {{ form.phone_number }}
            </div>
          </div>
          {% if account_type == 1 %}
            <div class="control-group">
              <div class="control-label" for="id_mentor">
              {{ form.mentor.label_tag }}
              </div>
              <div class="controls">
                {{ form.mentor }} <span>(Just leave this blank if you don't know what it is)<span>
              </div>
            </div>
      	  {% elif account_type == 2 %}
        	  <div class="control-group">
              <div class="control-label" for="id_mentor">
                <label>Your Vinely Pro (Email)</label>
              </div>
              <div class="controls">
                {{ form.mentor }} <span>(Just leave this blank if you don't know what it is)<span>
              </div>
            </div>
          {% endif %}
          <input type="hidden" name="password1" value="Sign Up" />
          <input type="hidden" name="password2" value="Sign Up" />
          <div class="form-actions">
            <div class="controls">
              <input class="btn btn-primary" type="submit" value="Sign Up" />
            </div>
          </div>

        </fieldset>
      </form>

    </div> <!-- .row -->
  {% endif %}
</div> <!-- container -->

{% endblock content %}

accounts/templates/accounts/verified_email.html
{% extends "winedora/base_html5.html" %}

{% block header %}
  <h1>Verified E-mail Address</h1>
{% endblock header %}

{% block content %}

<div class="container" data-spy="scroll" data-offset="50" data-target=".subnav">
    <div class="row">
      <div class="span8">
        Your new e-mail address has been verified and now usable.  Please use this new e-mail address to access your account.
      </div>
    </div>
    <div class="row">
      <div class="span8">
        <p>&nbsp;</p>
      </div>
    </div>
</div>

{% endblock content %}

accounts/templates/accounts/verify_eligibility.html
{% extends "accounts/base_my_account.html" %}

{% block right_content %}
      <form class="form-horizontal well" method="POST" action="{% url verify_eligibility %}">
          {% csrf_token %}

          {% if error %}
            <div class="alert alert-error">
              {{ error }}
            </div>
          {% endif %}
          {% if form.errors %}
            <div class="alert alert-error">
              {{ form.errors }}
            </div>
          {% endif %}

        <fieldset>
          <legend>Verify Eligibility</legend>
          <div class="control-group">
            <div class="controls">
              {{ form.user }}
            </div>
          </div>

          <div class="control-group">
            <div class="control-label" for="id_dob">
            {{ form.dob.label }}
            </div>
            <div class="controls">
              {{ form.dob }}
            </div>
          </div>
          <div class="control-group">
            <div class="control-label" for="id_gender">
            {{ form.gender.label }}
            </div>
            <div class="controls">
              {{ form.gender }}
            </div>
          </div>
          <div class="control-group">
            <div class="control-label" for="id_dl_number">
            {{ form.dl_number.label }}
            </div>
            <div class="controls">
              {{ form.dl_number }}
            </div>
          </div>
          <div class="control-group">
            <div class="control-label" for="id_zipcode">
            {{ form.zipcode.label }}
            </div>
            <div class="controls">
              {{ form.zipcode }}
            </div>
          </div>
          <div class="control-group">
            <div class="control-label" for="id_phone">
            {{ form.phone.label }}
            </div>
            <div class="controls">
              {{ form.phone }}
            </div>
          </div>
          <!-- TODO: need to put terms of service -->
          <div class="control-group">
            <div class="controls">
              <label class="checkbox inline">
              {{ form.accepted_tos }}
              {{ form.accepted_tos.label }}
              [<a href="{% url terms %}">Terms</a>]
              </label>
            </div>
          </div>
          <div class="control-group">
            <div class="controls">
              <label class="checkbox inline">
              {{ form.above_21 }}
              {{ form.above_21.label }}
              </label>
            </div>
          </div>
          <div class="form-actions">
            <div class="controls">
              <input class="btn btn-primary" type="submit" value="Submit" />
            </div>
          </div>
        </fieldset>
           
      </form>
{% endblock right_content %}