cms/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('cms.views',
    url(r'^$', 'template_list', name='template_list'),
    url(r'^list/$', 'template_list', name='template_list'),
    url(r'^list/(?P<type>\d)/$', 'template_list', name='template_list'),
    url(r'^edit/template/(?P<key>\w+)/$', 'edit_template', name='edit_template'),
)

coupon/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('coupon.views',
    url(r'^$', 'coupon_list', name="coupon_list"),
    url(r'^list/$', 'coupon_list', name="coupon_list"),
    url(r'^add/$', 'coupon_create', name="coupon_create"),
    url(r'^edit/(?P<coupon_id>\d+)/$', 'coupon_create', name="coupon_create"),
)

winedora/urls.py
from django.conf.urls import patterns, include, url
# from emailusernames.forms import EmailAuthenticationForm
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'winedora.views.home', name='home'),
    # url(r'^winedora/', include('winedora.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin_tools/', include('admin_tools.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'winedora.views.home', name='landing_page'),
    url(r'^pinterest-868f3.html$', 'winedora.views.pinterest'),
    url(r'^', include('main.urls')),
    url(r'^personality/', include('personality.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^support/', include('support.urls', namespace="support")),
    url(r'^social/', include('social.urls')),
    url(r'^cms/', include('cms.urls', namespace="cms")),
    url(r'^stripe/', include('stripecard.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^pro/', include('pro.urls', namespace="pro")),
    url(r'^coupon/', include('coupon.urls')),
    url(r'^landing/', include('landing.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

from api.tools import api
urlpatterns += patterns('',
    url(r'^api/', include(api.urls)),
    url(r'^api/spec/', include('tastypie_swagger.urls', namespace='tastypie_swagger')),
    url(r'^api/log/', include('api_logger.urls', namespace='api_logger')),
) + static('api/docs/', document_root="api_docs/_build/html/") + staticfiles_urlpatterns()

coupon/models.py
from django.db import models
from main.models import Product
# Create your models here.


class Coupon(models.Model):
  # from main.models import Product

  DURATION_CHOICES = (
      (0, 'One Time'),
      (1, 'Forever'),
      (2, 'Repeating'),
  )
  STRIPE_DURATION_CHOICES = {
      0: 'once',
      1: 'repeating',
      2: 'forever',
  }
  # APPLICATION_CHOICES = (
  #     (0, 'Tasting Kit'),
  #     (1, '3 Bottle VIP'),
  #     (2, '6 Bottles'),
  #     (3, '12 Bottles'),
  # )
  name = models.CharField(max_length=24)
  code = models.CharField(max_length=16, unique=True, verbose_name='Coupon Code')
  active = models.BooleanField(default=True, verbose_name='Enabled')
  duration = models.IntegerField(choices=DURATION_CHOICES, default=0)
  repeat_duration = models.IntegerField(default=0, help_text="If repeating, how long in months")
  amount_off = models.DecimalField(max_digits=10, decimal_places=2, default=0)
  percent_off = models.IntegerField(default=0)
  max_redemptions = models.IntegerField(default=1, verbose_name='Number of Uses', help_text='How many times can it be redeemed')
  redeem_by = models.DateField(verbose_name='Expiration Date')
  applies_to = models.ManyToManyField(Product)
  times_redeemed = models.IntegerField(default=0)
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)

coupon/forms.py
from django import forms
from django.utils import timezone

from coupon.models import Coupon
from main.models import Product


class CouponForm(forms.ModelForm):
  applies_to = forms.ModelMultipleChoiceField(queryset=Product.objects.filter(active=True).order_by('id'), widget=forms.CheckboxSelectMultiple)

  class Meta:
    model = Coupon
    exclude = ['times_redeemed', 'created', 'updated']

  def __init__(self, *args, **kwargs):
    super(CouponForm, self).__init__(*args, **kwargs)
    # self.fields['redeem_by'].widget.attrs['class'] = 'datepicker'
    self.fields['redeem_by'].widget.attrs = {
        'class': 'datepicker',
        'data-date-format': 'mm/dd/yyyy',
        'placeholder': 'MM/DD/YYYY',
    }

    if kwargs.get('instance'):
      self.fields['code'].widget.attrs['readonly'] = True

  def clean_max_redemptions(self):
    cleaned_data = self.cleaned_data.get('max_redemptions', 0)
    if cleaned_data < 1:
      raise forms.ValidationError(u'Max redemptions must be 1 or more.')
    return cleaned_data

  def clean_redeem_by(self):
    cleaned_data = self.cleaned_data.get('redeem_by')
    today = timezone.now().date()
    if cleaned_data <= today:
      raise forms.ValidationError(u'Date must be in future.')

    return cleaned_data

  def clean(self):
    cleaned_data = super(CouponForm, self).clean()

    if cleaned_data.get('duration') == 2 and cleaned_data.get('repeat_duration') == 0:
      self._errors['repeat_duration'] = u'You must specify a repeat duration greater than 0 if it is repeating.'
      # raise forms.ValidationError(u'You must specify a repeat duration greater than 0 if it is repeating.')

    if cleaned_data.get('amount_off') > 0 and cleaned_data.get('percent_off'):
      self._errors['amount_off'] = u'You can only set either amount off or percent off but not both.'
      self._errors['percent_off'] = u'You can only set either amount off or percent off but not both.'
      # raise forms.ValidationError(u'You can only set either amount off or percent off but not both.')

    if cleaned_data.get('amount_off') == 0 and cleaned_data.get('percent_off') == 0:
      self._errors['amount_off'] = u'You must set a value of 1 or more for either amount off or percent off.'
      self._errors['percent_off'] = u'You must set a value of 1 or more for either amount off or percent off.'
      # raise forms.ValidationError(u'You must set a value of 1 or more for either amount off or percent off.')

    return cleaned_data

coupon/views.py
# Create your views here.

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.contrib.admin.views.decorators import staff_member_required
from django.core.urlresolvers import reverse
# from django.conf import settings
from django.contrib import messages

from coupon.tables import CouponTable
from coupon.models import Coupon
from coupon.forms import CouponForm

# import time
# import stripe

import logging

logger = logging.getLogger(__name__)


@staff_member_required
def coupon_list(request):
  data = {}
  coupons = Coupon.objects.all()
  data['table'] = CouponTable(coupons)
  return render(request, 'coupon/coupon_list.html', data)


@staff_member_required
def coupon_create(request, coupon_id=None):
  data = {}

  coupon = None
  if coupon_id:
    coupon = get_object_or_404(Coupon, pk=coupon_id)
    # messages.warning(request, 'Note that changing the Coupon code will make it unusable for users that might already have the Coupon.')

  initial = {'redeem_by': coupon.redeem_by.strftime("%m/%d/%Y") if coupon and coupon.redeem_by else ''}
  form = CouponForm(request.POST or None, instance=coupon, initial=initial)
  data['form'] = form
  data['coupon'] = coupon

  if form.errors.get('__all__'):
    messages.warning(request, form.errors['__all__'])

  if form.is_valid():
    coupon = form.save(commit=False)
    if coupon.duration == Coupon.STRIPE_DURATION_CHOICES[0][0]:
      coupon.max_redemptions = 1
    coupon.save()
    form.save_m2m()

    # NOTE: disabled creating coupon in stripe - can implement the upto 50% limit on stripe
    # so handling this on Vinely

    # coupon = form.save(commit=False)

    # create coupon in stripe as well
    # stripe.api_key = settings.STRIPE_SECRET_CA
    # coupon_config = {
    #     'id': coupon.code,
    #     'currency': 'usd',
    #     'duration': Coupon.STRIPE_DURATION_CHOICES[coupon.duration],
    #     'redeem_by': int(time.mktime(coupon.redeem_by.timetuple())),
    # }
    # if coupon.amount_off > 0:
    #   coupon_config['amount_off'] = coupon.amount_off
    #   # coupon.percent_off = 0
    # else:
    #   coupon_config['percent_off'] = coupon.percent_off
    #   # coupon.amount_off = 0

    # if coupon.duration == Coupon.STRIPE_DURATION_CHOICES[2][0]:
    #   coupon_config['duration_in_months'] = coupon.repeat_duration

    # if coupon.max_redemptions > 0:
    #   coupon_config['max_redemptions'] = coupon.max_redemptions

    # try:
    #   if coupon_id:
    #     stripe_coupon = stripe.Coupon.retrieve(coupon.code)
    #     stripe_coupon.delete()
    # except Exception, e:
    #   pass

    # try:
    #   stripe.Coupon.create(**coupon_config)
    #   coupon.save()
    #   form.save_m2m()
    # except Exception, e:
    #   logger.error(e)
    #   messages.warning(request, 'Error saving the coupon on stripe. %s' % e)
    #   return render(request, 'coupon/coupon_create.html', data)

    # if all is well clear the warning about changing coupon code. Cleared by iterating
    # storage = messages.get_messages(request)
    # for x in storage:
    #   pass

    return HttpResponseRedirect(reverse('coupon_list'))

  return render(request, 'coupon/coupon_create.html', data)

coupon/templates/coupon/coupon_create.html
{% extends "winedora/base_html5.html" %}

{% load currency %}

{% load static %}

{% block additional_styles %}
  <link rel="stylesheet" href="{% static "datepicker/css/datepicker.css" %}">
  <style type="text/css">
    {% if coupon.duration != 2 %}
      .repeat-duration {
        display: none;
      }
    {% endif %}
    .form-horizontal ul {
      list-style: none;
    }
  </style>
{% endblock additional_styles %}

{% block content %}

<div class="container">
  <div class="row">
    <form class="form-horizontal" method="POST" action="{{ app_path }}">
      {% csrf_token %}
      <div class="span10 offset2">
        <div class="control-group {% if form.name.errors %}error{% endif %}">
          <div class="control-label" for="id_name">{{ form.name.label }}</div>
          <div class="controls">
            {{ form.name }}
            {% if form.name.errors %}
              <span class="help-inline">
                {{ form.name.errors }}
              </span>
            {% endif %}
          </div>
        </div>
        <div class="control-group {% if form.code.errors %}error{% endif %}">
          <div class="control-label" for="id_code">{{ form.code.label }}</div>
          <div class="controls">
            {{ form.code }}
            {% if form.code.errors %}
              <span class="help-inline">
                {{ form.code.errors }}
              </span>
            {% endif %}
          </div>
        </div>
        <div class="control-group {% if form.active.errors %}error{% endif %}">
          <div class="control-label" for="id_active">{{ form.active.label }}</div>
          <div class="controls">
            {{ form.active }} 
            {% if form.active.errors %}
              <span class="help-inline">
                {{ form.active.errors }}
              </span>
            {% endif %}
          </div>
        </div>
        <div class="control-group {% if form.duration.errors %}error{% endif %}">
          <div class="control-label" for="id_duration">{{ form.duration.label }}</div>
          <div class="controls">
            {{ form.duration }} 
            {% if form.duration.errors %}
              <span class="help-inline">
                {{ form.duration.errors }}
              </span>
            {% endif %}
          </div>
        </div>
        <div class="control-group repeat-duration {% if form.repeat_duration.errors %}error{% endif %}">
          <div class="control-label" for="id_repeat_duration">{{ form.repeat_duration.label }}</div>
          <div class="controls">
            {{ form.repeat_duration }} 
            <span class="help-inline">{{ form.repeat_duration.help_text }}</span>
            {% if form.repeat_duration.errors %}
              <span class="help-inline">
                {{ form.repeat_duration.errors }}
              </span>
            {% endif %}
          </div>
        </div>
        <fieldset>
          <legend>Discount type and amount</legend>
          <div class="control-group {% if form.amount_off.errors %}error{% endif %}">
            <div class="control-label" for="id_amount_off">{{ form.amount_off.label }}</div>
            <div class="controls">
              <!-- {{ form.amount_off }}  -->
              <div class="input-prepend">
                  <span class="add-on">$</span>
                  <input class="span2" type="text" name="amount_off" 
                    value="{% if coupon.amount_off %}{{ coupon.amount_off }}{% else %}0{% endif %}" id="id_amount_off">
              </div>
              {% if form.amount_off.errors %}
                <span class="help-inline">
                  {{ form.amount_off.errors }}
                </span>
              {% endif %}
            </div>
          </div>
          <h2 style="margin-left: 120px; margin-top: -22px;"><small>OR</small></h2>
          <div class="control-group {% if form.percent_off.errors %}error{% endif %}">
            <div class="control-label" for="id_percent_off">{{ form.percent_off.label }}</div>
            <div class="controls">
              <!-- {{ form.percent_off }}  -->
              <div class="input-append">
                  <input class="span1" type="text" name="percent_off" 
                    value="{% if coupon.percent_off %}{{ coupon.percent_off }}{% else %}0{% endif %}" id="id_percent_off">
                  <span class="add-on">%</span>
              </div>
              {% if form.percent_off.errors %}
                <span class="help-inline">
                  {{ form.percent_off.errors }}
                </span>
              {% endif %}
            </div>
          </div>
        </fieldset>
        <div class="control-group {% if form.max_redemptions.errors %}error{% endif %}">
          <div class="control-label" for="id_max_redemptions">{{ form.max_redemptions.label }}</div>
          <div class="controls">
            {{ form.max_redemptions }}
            <span class="help-inline">{{ form.max_redemptions.help_text }}</span>
            {% if form.max_redemptions.errors %}
              <span class="help-inline">
                {{ form.max_redemptions.errors }}
              </span>
            {% endif %}
          </div>
        </div>
        <div class="control-group {% if form.redeem_by.errors %}error{% endif %}">
          <div class="control-label" for="id_redeem_by">{{ form.redeem_by.label }}</div>
          <div class="controls">
            {{ form.redeem_by }}
            {% if form.redeem_by.errors %}
              <span class="help-inline">
                {{ form.redeem_by.errors }}
              </span>
            {% endif %}
          </div>
        </div>
        <div class="control-group {% if form.applies_to.errors %}error{% endif %}">
          <div class="control-label" for="id_applies_to">{{ form.applies_to.label }}</div>
          <div class="controls">
            {{ form.applies_to }} 
            {% if form.applies_to.errors %}
              <span class="help-inline">
                {{ form.applies_to.errors }}
              </span>
            {% endif %}
          </div>
        </div>
        <div class="control-group {% if form.applies_to.errors %}error{% endif %}">
          <div class="controls">
            <button type="submit" class="btn btn-primary">Update</btn>
          </div>
        </div>
        
      </div>
    </form>
  </div>
</div>

{% endblock %}

{% block additional_scripts %}
  <script type="text/javascript" src="{% static "datepicker/js/bootstrap-datepicker.js" %}"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      if ($('#id_duration').val() == 2) {
        $('.repeat-duration').show('fast');
      }
      $('.datepicker').datepicker();
      $('#id_duration').change(function() {
        if ($(this).val() == 2) {
          $('.repeat-duration').show('fast');
        }
        else {
          $('.repeat-duration').hide('fast');
          $('#id_repeat_duration').val(0);
        }
      });
    });
  </script>
{% endblock additional_scripts %}

coupon/templates/coupon/coupon_list.html
{% extends "winedora/base_html5.html" %}

{% load currency %}

{% load render_table from django_tables2 %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="span12">
      <a href="{% url coupon_create %}" class="btn btn-primary pull-right">Add</a>
    </div>
  </div>
  <div class="row">
    <div class="span12">
      {% render_table table %}
    </div>
  </div>
</div>

{% endblock %}