cms/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('cms.views',
    url(r'^$', 'template_list', name='template_list'),
    url(r'^list/$', 'template_list', name='template_list'),
    url(r'^list/(?P<type>\d)/$', 'template_list', name='template_list'),
    url(r'^edit/template/(?P<key>\w+)/$', 'edit_template', name='edit_template'),
)

support/urls.py
from django.conf.urls import patterns, include, url
from support.views import view_party_detail
urlpatterns = patterns('support.views',
    url(r'^$', 'admin_index', name='admin_index'),
    url(r'^subscriptions/manage/$', 'manage_subscriptions', name='manage_subscriptions'),
    url(r'^email/list/$', 'list_emails', name='list_emails'),
    url(r'^email/(?P<email_id>\d+)/$', 'view_email', name='view_email'),
    url(r'^download/users/$', 'download_users', name='download_users'),
    url(r'^download/users/party/(?P<party_id>\d+)/$', 'download_users_from_party', name="download_users_from_party"),
    url(r'^download/parties/$', 'download_parties', name='download_parties'),
    url(r'^download/orders/$', 'download_orders', name='download_orders'),
    url(r'^users/$', 'view_users', name='view_users'),
    url(r'^users/(?P<user_id>\d+)/$', 'view_user_details', name='view_user_details'),
    url(r'^parties/$', 'view_parties', name='view_parties'),
    url(r'^parties/(?P<party_id>\d+)/$', 'view_party_detail', name='view_party_detail'),

    url(r'^orders/$', 'view_orders', name='view_orders'),
    url(r'^orders/(?P<order_id>\d+)/$', 'view_orders', name='view_orders'),
    url(r'^order/refund/(?P<order_id>\d+)/$', 'refund_order', name='refund_order'),
    url(r'^order/edit/$', 'edit_order', name='edit_order'),
    url(r'^order/edit/(?P<order_id>\d+)/$', 'edit_order', name='edit_order'),
    url(r'^order/rate/(?P<order_id>\d+)/$', 'rate_order', name='rate_order'),
    url(r'^order/tastekit/(?P<order_id>\d+)/$', 'fulfill_taste_kit', name='fulfill_taste_kit'),
    url(r'^orders/past/$', 'view_past_orders', name='view_past_orders'),
    url(r'^orders/past/(?P<order_id>\d+)/$', 'view_past_orders', name='view_past_orders'),
    url(r'^wine/inventory/$', 'wine_inventory', name='wine_inventory'),
    url(r'^download/ready/orders/$', 'download_ready_orders', name='download_ready_orders'),
)

winedora/urls.py
from django.conf.urls import patterns, include, url
# from emailusernames.forms import EmailAuthenticationForm
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'winedora.views.home', name='home'),
    # url(r'^winedora/', include('winedora.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin_tools/', include('admin_tools.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'winedora.views.home', name='landing_page'),
    url(r'^pinterest-868f3.html$', 'winedora.views.pinterest'),
    url(r'^', include('main.urls')),
    url(r'^personality/', include('personality.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^support/', include('support.urls', namespace="support")),
    url(r'^social/', include('social.urls')),
    url(r'^cms/', include('cms.urls', namespace="cms")),
    url(r'^stripe/', include('stripecard.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^pro/', include('pro.urls', namespace="pro")),
    url(r'^coupon/', include('coupon.urls')),
    url(r'^landing/', include('landing.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

from api.tools import api
urlpatterns += patterns('',
    url(r'^api/', include(api.urls)),
    url(r'^api/spec/', include('tastypie_swagger.urls', namespace='tastypie_swagger')),
    url(r'^api/log/', include('api_logger.urls', namespace='api_logger')),
) + static('api/docs/', document_root="api_docs/_build/html/") + staticfiles_urlpatterns()

support/models.py
from django.db import models
from django.conf import settings

# Create your models here.
from personality.models import Wine, TastingKit


class Email(models.Model):

  subject = models.CharField(max_length=128)
  sender = models.CharField(max_length=64)
  recipients = models.CharField(max_length=512)
  text = models.TextField()
  html = models.TextField()
  timestamp = models.DateTimeField(auto_now_add=True)

  def __unicode__(self):
    return "%s TO %s" % (self.subject, self.recipients)

  def recipients_list(self):
    return eval(self.recipients)


class InventoryUpload(models.Model):
  inventory_file = models.FileField(verbose_name="Upload File:", help_text="Select inventory file to upload", upload_to="wine_inventory/")
  comment = models.CharField(blank=True, null=True, max_length=128)
  created = models.DateTimeField(auto_now_add=True)


class WineInventory(models.Model):
  wine = models.OneToOneField(Wine)
  on_hand = models.IntegerField(default=0)
  updated = models.DateTimeField(auto_now=True)
  created = models.DateTimeField(auto_now_add=True)

  class Meta:
    verbose_name_plural = u'Wine Inventory'


class TastingKitInventory(models.Model):
  tasting_kit = models.OneToOneField(TastingKit)
  on_hand = models.IntegerField(default=0)
  updated = models.DateTimeField(auto_now=True)
  created = models.DateTimeField(auto_now_add=True)

  class Meta:
    verbose_name_plural = u'Tasting Kit Inventory'

support/forms.py
from django import forms
from django.db.models import Q

from support.models import InventoryUpload
from main.models import SelectedWine, Order, SelectedTastingKit
from personality.models import WineRatingData, Wine


class InventoryUploadForm(forms.ModelForm):

  class Meta:
    model = InventoryUpload
    exclude = ['created']


class ChangeFulfillStatusForm(forms.ModelForm):

  class Meta:
    model = Order
    fields = ['fulfill_status']


class SelectedWineRatingForm(forms.ModelForm):
  """
    Used to rate the wines that have been shipped and consumed
  """
  record_id = forms.IntegerField(required=False)

  class Meta:
    model = SelectedWine

  def __init__(self, *args, **kwargs):
    super(SelectedWineRatingForm, self).__init__(*args, **kwargs)
    self.fields['record_id'].widget = forms.HiddenInput()
    self.fields['order'].widget = forms.HiddenInput()
    self.fields['wine'].widget = forms.HiddenInput()
    #self.fields['wine'].widget = forms.TextInput()
    #self.fields['wine'].widget.attrs['disabled'] = True
    if 'wine_name' in self.initial:
      self.fields['wine'].label = self.initial['wine_name']
    self.fields['overall_rating'].widget = forms.RadioSelect(choices=WineRatingData.LIKENESS_CHOICES)
    self.fields['overall_rating'].widget.attrs['class'] = "inline-radio"


class SelectWineForm(forms.ModelForm):
  """
    Used to manually fulfill wine for an order

    Very hacky.
  """
  record_id = forms.IntegerField(required=False)

  class Meta:
    model = SelectedWine
    exclude = ['order', 'overall_rating']

  def __init__(self, *args, **kwargs):
    super(SelectWineForm, self).__init__(*args, **kwargs)
    self.fields['record_id'].widget = forms.HiddenInput()

    if 'wine' in self.initial:
      # this is needed to cover the case where a wine is already selected and inventory is 0
      # we still need to show the wine selected
      wines = Wine.objects.filter(Q(is_taste_kit_wine=False, wineinventory__on_hand__gt=0) | Q(id=self.initial['wine']))
    else:
      # used to show list of all wines that are in inventory
      wines = Wine.objects.filter(is_taste_kit_wine=False, wineinventory__on_hand__gt=0)

    # in order filter the qualified wines by one's personal preferences
    if 'color_filter' in self.initial:
      #print self.initial['color_filter']
      wines = wines.filter(color=self.initial['color_filter'])
    if 'sparkling_filter' in self.initial:
      if not self.initial['sparkling_filter']:
        wines = wines.filter(sparkling=self.initial['sparkling_filter'])
    if 'category_filter' in self.initial:
      wines = wines.filter(vinely_category__in=self.initial['category_filter'])

    self.fields['wine'].queryset = wines


class SelectTastingKitForm(forms.ModelForm):

  class Meta:
    model = SelectedTastingKit
    exclude = ['order']


class RefundForm(forms.ModelForm):
  full_refund = forms.BooleanField(required=False)

  class Meta:
    model = Order
    fields = ['refund_amount']

support/templates/support/admin_index.html
{% extends "winedora/base_html5.html" %}

{% block additional_styles %}
  <style type="text/css">
    a:visited {
      color: #DD4040;
      text-decoration: none;
    }
  </style>
{% endblock additional_styles %}

{% block header %}
    <h1 class="headline">Vinely Administration</h1>
{% endblock %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="span4">
        <h1>Communication</h1>
        <ul>
          <li><a href="{% url cms:template_list %}">Manage E-mail and Web Templates</a></li>
          <li><a href="{% url support:list_emails %}">View E-mails</a></li>
          <li><a href="{% url support:manage_subscriptions %}">Manage Subscriptions</a></li>
        </ul>
      </div>
      <div class="span4">
        <h1>Users</h1>
        <ul>
          <li><a href="{% url support:view_users %}">Manage</a></li>
          {# <li><a href="#">Reports</a></li> #}
        </ul>
      </div>
      <div class="span4">
        <h1>Pros</h1>
        <ul>
          {# <li><a href="#">Manage</a></li> #}
          <li><a href="{% url pro:pro_home %}">Reports</a></li>
        </ul>
      </div>
    </div>

    <div class="row">
      <div class="span4">
        <h1>Fulfillment</h1>
        <ul>        
          <li><a href="{% url support:wine_inventory %}">Wine Inventory Management</a></li>
          <li><a href="{% url support:view_orders %}">All Orders</a></li>
          <li><a href="{% url support:view_past_orders %}">Exported Orders</a></li>
        </ul>
      </div>
      <div class="span4">
        &nbsp;
        <h1>Parties</h1>
        <ul>
          <li><a href="{% url support:view_parties %}">Manage</a></li>
          <li><a href="#">Reports</a></li>
        </ul>
      </div>
      <div class="span3">
        &nbsp;
        {% comment %}
        <h1>Events</h1>
        <ul>
          <li><a href="#">Manage</a></li>
          <li><a href="#">Reports</a></li>
        </ul>
        {% endcomment %}
      </div>
    </div>
  </div>

{% endblock %}

support/templates/support/edit_order.html
{% extends "winedora/base_html5.html" %}

{% block header %}
  <h1 class="headline">Edit Order</h1>

{% endblock header %}

{% block content %}

<div class="container" data-spy="scroll" data-offset="50" data-target=".subnav">
  <div class="row">
    <div class="span6">
      &nbsp;
    </div>
    <div class="span6">
      <div class="pull-right">
        <a href="{% url support:admin_index %}">Support Home</a> |
        <a href="{% url support:wine_inventory %}">Wine Inventory</a> |
        <a href="{% url support:view_orders %}">Orders</a>
      </div>
    </div>

    <form method="POST" action="">
      {% csrf_token %}
      <!-- include most content in the form --> 

      <div class="span12">
        <section id="order-details">
          <legend>Order Details</legend>
          <div class="span12">
            <div class="row">
              <div class="span4">
                Order ID: {{ order.vinely_order_id }}
              </div>
              <div class="span4">
                Ordered By: {{ order.receiver_info }}
              </div>
              <div class="span4">
                Order Date: {{ order.order_date|date:"M d, Y" }}
              </div>
            </div>
            <div class="vertical-space-20">
              &nbsp;
            </div>
            <div class="row">
              <div class="span8">
                Product: {{ order.cart }}
              </div>
              <div class="span4">
                Subscription: {{ recurring }}
              </div>
            </div>
            <div class="vertical-space-20">
              &nbsp;
            </div>            
            <div class="row">
              <div class="span4">
                      Taste Code: 
                        {% with rating_summary=receiver_profile.personality_rating_code %}
                          <a href="#" class="taste-code" rel="popover" data-placement="bottom" data-trigger="hover"
                              data-content="{{ rating_summary.1 }}">
                            {{ rating_summary.0 }}</a>
                        {% endwith %}                
              </div>
              <div class="span4">
                Red/White: {{ receiver_profile.order_customization_pref }}
              </div>
              <div class="span4">
                Bubbles: {{ customization.get_sparkling_display }}
              </div>
            </div>
            <div class="vertical-space-20">
              &nbsp;
            </div>            
            <div class="row">
              <div class="span4">
                Wine Personality: {{ receiver_profile.wine_personality }}
              </div>
              <div class="span2">
                {{ status_change_form.fulfill_status.label_tag }} 
              </div>
              <div class="span6">
                {{ status_change_form.fulfill_status }}
              </div>
            </div>
          </div>
        </section>
      </div>

      <div class="span12">
        <section id="select-wine">
          <legend>Select Wine</legend>

          {{ formset.management_form }}
          {{ formset.non_form_errors }}

          {% for form in formset.forms %}
            {% if forloop.counter0|divisibleby:"2" %}
              <div class="row">
            {% endif %}
              <div class="span6">
                <!-- {{ form.non_field_errors }} -->
                <!-- {{ form.errors }} -->
                {{ form.title }}
                {{ form.description }}
                {{ form.as_table }}
              </div>
            {% if forloop.counter|divisibleby:"2" or forloop.last %}
              </div>
            {% endif %}         
          {% endfor %}

          <div class="form-actions">
            <input type="submit" class="btn btn-primary" value="Save">
          </div>
        </section>
      </div>

    </form>

    <div class="span12">
      <section id="past-ratings">
        <legend>Past Ratings</legend>
        <div class="span12">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Wine Name</th>
                <th>Rating</th>
                <th>Date</th>
              </tr>
            </thead>
            <tbody>
              {% for rating in past_ratings %} 
                <tr>
                  <td>
                    {{ rating.wine }}
                  </td>
                  <td>
                    [{{ rating.overall_rating }}] {{ rating.get_overall_rating_display }} 
                  </td>
                  <td>
                    {{ rating.timestamp }}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  </div> <!-- outermost row -->
</div>

<div class="vertical-space">
  &nbsp;
</div>
{% endblock content %}


{% block additional_scripts %}
  <script type="text/javascript">
    $(document).ready(function(){
      $('.taste-code').popover();
    });
  </script>
{% endblock additional_scripts %}

support/templates/support/fulfill_taste_kit.html
{% extends "winedora/base_html5.html" %}

{% block header %}
  <h1 class="headline">Edit Order</h1>

{% endblock header %}

{% block content %}

<div class="container" data-spy="scroll" data-offset="50" data-target=".subnav">
  <div class="row">
    <div class="span6">
      &nbsp;
    </div>
    <div class="span6">
      <div class="pull-right">
        <a href="{% url support:admin_index %}">Support Home</a> |
        <a href="{% url support:wine_inventory %}">Wine Inventory</a> |
        <a href="{% url support:view_orders %}">Orders</a>
      </div>
    </div>

    <form method="POST" action="">
      {% csrf_token %}
      <!-- include most content in the form --> 

      <div class="span12">
        <section id="order-details">
          <legend>Order Details</legend>
          <div class="span12">
            <div class="row">
              <div class="span4">
                Order ID: {{ order.vinely_order_id }}
              </div>
              <div class="span4">
                Ordered By: {{ order.receiver_info }}
              </div>
              <div class="span4">
                Order Date: {{ order.order_date|date:"M d, Y" }}
              </div>
            </div>
            <div class="vertical-space-20">
              &nbsp;
            </div>
            <div class="row">
              <div class="span6">
                Product: {{ order.cart }}
              </div>
              <div class="span3">
                Quantity: {{ order.quantity_summary }}
              </div>
              <div class="span3">
                Subscription: {{ recurring }}
              </div>
            </div>
            <div class="vertical-space-20">
              &nbsp;
            </div>            
            <div class="row">
              <div class="span4">
                      Taste Code: 
                        {% with rating_summary=receiver_profile.personality_rating_code %}
                          <a href="#" class="taste-code" rel="popover" data-placement="bottom" data-trigger="hover"
                              data-content="{{ rating_summary.1 }}">
                            {{ rating_summary.0 }}</a>
                        {% endwith %}                
              </div>
              <div class="span4">
                Red/White: {{ receiver_profile.order_customization_pref }}
              </div>
              <div class="span4">
                Bubbles: {{ customization.get_sparkling_display }}
              </div>
            </div>
            <div class="vertical-space-20">
              &nbsp;
            </div>            
            <div class="row">
              <div class="span4">
                Wine Personality: {{ receiver_profile.wine_personality }}
              </div>
              <div class="span2">
                {{ status_change_form.fulfill_status.label_tag }} 
              </div>
              <div class="span6">
                {{ status_change_form.fulfill_status }}
              </div>
            </div>
          </div>
        </section>
      </div>

      <div class="span12">
        <section id="select-wine">
          <legend>Select Taste Kit</legend>

              {% for field in select_tasting_kit_form %}
          <div class="row">
            <div class="span12">
                <div class="span2">
                  &nbsp;
                </div>
                <div class="span2">
                {{ field.label_tag }}
                </div>
                <div class="span6">
                {{ field }}
                </div>
            </div>
          </div>
              {% endfor %} 

          <div class="form-actions">
            <input type="submit" class="btn btn-primary" value="Save">
          </div>
        </section>
      </div>

    </form>

    <div class="span12">
      <section id="past-ratings">
        <legend>Past Ratings</legend>
        <div class="span12">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Wine Name</th>
                <th>Rating</th>
                <th>Date</th>
              </tr>
            </thead>
            <tbody>
              {% for rating in past_ratings %} 
                <tr>
                  <td>
                    {{ rating.wine }}
                  </td>
                  <td>
                    [{{ rating.overall_rating }}] {{ rating.get_overall_rating_display }} 
                  </td>
                  <td>
                    {{ rating.timestamp }}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  </div> <!-- outermost row -->
</div>

<div class="vertical-space">
  &nbsp;
</div>
{% endblock content %}


{% block additional_scripts %}
  <script type="text/javascript">
    $(document).ready(function(){
      $('.taste-code').popover();
    });
  </script>
{% endblock additional_scripts %}

support/templates/support/list_emails.html
{% extends "winedora/base_html5.html" %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="span12">
        <form method="get" class="form-horizontal" action="">
          <input type="text" name="email" value="{{ search_email }}" placeholder="Search for email address" />
          <button type="submit" class="btn btn-primary">Search</button>
        </form>
        <table class="table">
          <thead>
            <tr>
            <th>ID</th>
            <th>Subject</th>
            <th>Recipients</th>
            <th>Date Sent</th>
            </tr>
          </thead>
          <tbody>
          {% for email in emails %}
          <tr>
            <td><a href="{% url support:view_email email.id %}">{{ email.id }}</a></td>
            <td><a href="{% url support:view_email email.id %}">{{ email.subject }}</a></td>
            <td>
              {% for address in email.recipients_list %}
                {% if forloop.last %}
                  {{ address }}
                {% else %}
                  {{ address }},
                {% endif %}
              {% endfor %}
            </td>
            <td>{{ email.timestamp }}</td>
          </tr>
          {% endfor %}
          </tbody>
        </table>

        <div class="row">
          <div class="span12">
            <a href=".">First</a> | 
            <a href="{% if page.has_previous %}./?p={{ page.previous_page_number }}{% else %}#{% endif %}">Previous</a> |
            <span>{{ page }}</span> | 
            <a href="{% if page.has_next %}./?p={{ page.next_page_number }}{% else %}#{% endif %}">Next</a> | 
            <a href="{% if page.has_other_pages %}./?p={{ page_count }}{% else %}#{% endif %}">Last</a>
            <p></p>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

support/templates/support/manage_subscriptions.html
{% extends "winedora/base_html5.html" %}

{% block content %}
  <div class="container">
    <h1>Currently Active Subscriptions</h1>
    <div class="row">
      <div class="span12">
          <table class="table">
            <thead>
              <tr>
              <th>E-mail</th>
              <th>Full name</th>
              <th>State</th>
              <th>Quantity</th>
              <th>Frequency</th>
              <th>Next Invoice Date</th>
              <th>Updated Time</th>
              </tr>
            </thead>
            <tbody>
            {% for subscription in subscriptions %}
            <tr>
              <td><a href="{% url admin:accounts_subscriptioninfo_change subscription.id %}">{{ subscription.user.email }}</a></td>
              <td>{{ subscription.user.first_name }} {{ subscription.user.last_name }}</td>
              <td>{{ subscription.user.get_profile.shipping_address.state }}</td>
              <td>{{ subscription.get_quantity_display }}</td>
              <td>{{ subscription.get_frequency_display }}</td>
              <td>{{ subscription.next_invoice_date }}</td>
              <td>{{ subscription.updated_datetime }}</td>
            </tr>
            {% endfor %}
            </tbody>
          </table>

          <div class="row">
            <div class="span12">
              <a href=".">First</a> | 
              <a href="{% if page.has_previous %}./?p={{ page.previous_page_number }}{% else %}#{% endif %}">Previous</a> |
              <span>{{ page }}</span> | 
              <a href="{% if page.has_next %}./?p={{ page.next_page_number }}{% else %}#{% endif %}">Next</a> | 
              <a href="{% if page.has_other_pages %}./?p={{ page_count }}{% else %}#{% endif %}">Last</a>
              <p></p>
            </div>
          </div>
      </div>
    </div>
  </div>

{% endblock %}

support/templates/support/refund_order_modal.html
{% load currency %}
<div id="update_age" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h2 class="center">Refund: Order # - {{ order.vinely_order_id }}</h2>
  </div>
  <div class="modal-body">
    <form method="POST" class="form-horizontal" action="{% url support:refund_order order.id %}?next={{ previous_page }}">
      {% csrf_token %}
      {{ refund_form.order }}
      <div class="control-group">
        <div class="control-label">Order Amount:</div>
        <div class="controls">
          $<span id="amount">{{ order.cart.total }}</span>
        </div>
      </div>
      <div class="control-group">
        <div class="control-label">{{ refund_form.full_refund.label }}</div>
        <div class="controls"
          onclick="javascript:$('#id_refund_amount').prop('disabled', $('#id_full_refund').prop('checked')); $('#id_refund_amount').val($('#amount').text())">
          {{ refund_form.full_refund }}
        </div>
      </div>
      <div class="control-group">
        <div class="control-label">{{ refund_form.refund_amount.label }}</div>
        <div class="controls">
          {{ refund_form.refund_amount }}
        </div>
      </div>
      <div class="modal-footer">
        <button type="submit" name="refund" class="btn btn-primary" value="refund">Refund</button>
      </div>
    </form>
  </div>
</div>

support/templates/support/user_overview.html
{% extends "winedora/base_html5.html" %}

{% load render_table from django_tables2 %}

{% load static %}

{% block additional_styles %}

<link rel="stylesheet" href="{% static "django_tables2/themes/paleblue/css/screen.css" %}"/>

<style type="text/css">
  .table-container {
    width: 100%;
  }
</style>
{% endblock %}

{% block header %}
  <h1 class="headline">User overview</h1>
{% endblock header %}

{% block content %}

<div class="container" data-spy="scroll" data-offset="50" data-target=".subnav">
  <div class="row">
    <div class="span12">
      {% render_table users_table %}
    </div>
  </div> <!-- .row -->

</div>
{% endblock content %}

support/templates/support/view_orders.html
{% extends "winedora/base_html5.html" %}

{% load render_table from django_tables2 %}
{% load static %}

{% block additional_styles %}
  <link rel="stylesheet" href="{% static "django_tables2/themes/paleblue/css/screen.css" %}"/>
  <style type="text/css">
    div.table-container {
      display: block;
    }
  </style>
{% endblock %}

{% block header %}
  <h1 class="headline">All Orders</h1>

{% endblock header %}

{% block content %}

<div class="container" data-spy="scroll" data-offset="50" data-target=".subnav">
  <form class="form-horizontal" method="post" action="{% url support:download_ready_orders %}">
    {% csrf_token %}
    <div class="row">
      <div class="span6">
        &nbsp;
      </div>
      <div class="span6">
        <div class="pull-right">
          <a href="{% url support:admin_index %}">Support Home</a> |
          <a href="{% url support:wine_inventory %}">Wine Inventory</a>
          {# <a href="{% url support:download_ready_orders %}">Export Orders</a> #}
        </div>
      </div>
    </div>
    <div class="vertical-space"></div>
    <div class="row">
      <div class="span3 offset10">
        <button type="submit" class="btn btn-primary">Export Orders</button>
      </div>
    </div>
    <div class="vertical-space">
      &nbsp;
    </div> 
    <hr>
    <div class="row">
      <div class="span12">
        {% render_table orders %} 
      </div>
    </div>
  </form>
</div>

<div class="vertical-space">
  &nbsp;
</div>

{% endblock %}

{% block additional_scripts %}
  <script type="text/javascript">
    $(document).ready(function() {
      $('.all-orders').click(function(e) {
        var state = $(this).prop('checked');
        $('.order').prop('checked', state);
      });
    });
  </script>
{% endblock additional_scripts %}
  

support/templates/support/view_parties.html
{% extends "winedora/base_html5.html" %}

{% load render_table from django_tables2 %}

{% load static %}

{% block additional_styles %}

<link rel="stylesheet" href="{% static "django_tables2/themes/paleblue/css/screen.css" %}"/>

<style type="text/css">
  .table-container {
    width: 100%;
  }
</style>
{% endblock %}

{% block header %}
  <h1 class="headline">Parties</h1>
{% endblock header %}

{% block content %}

<div class="container" data-spy="scroll" data-offset="50" data-target=".subnav">
  <div class="row">
    <div class="span12">
      {% render_table parties_table %}
    </div>
  </div> <!-- .row -->

</div>
{% endblock content %}

support/templates/support/wine_inventory.html
{% extends "winedora/base_html5.html" %}

{% load render_table from django_tables2 %}

{% block header %}
  <h1 class="headline">Wine Inventory</h1>
{% endblock header %}

{% block content %}

<div class="container" data-spy="scroll" data-offset="50" data-target=".subnav">

  <!-- upload file -->
  <div class="row">
    <div class="span6">
      <form class="form-horizontal" method="POST" action="{{ app_path }}" enctype="multipart/form-data">
        {% csrf_token %}
        <span class="help-inline">{{ form.inventory_file.help_text }}</span>
        <div class="control-group">
            {{ form.non_field_errors }}
          <label class="control-label" for="id_inventory_file">
            {{ form.inventory_file.label_tag }} 
          </label>
          <div class="controls">
            {{ form.inventory_file.errors }}
            {{ form.inventory_file }}
          </div>
        </div>
        <div class="control-group">
           <label class="control-label" for="id_comment">
            {{ form.comment.label_tag }} 
          </label>         
           <div class="controls">
            {{ form.comment.errors }}
            {{ form.comment }}
          </div>         
        </div>

        <div class="form-actions">
          <button type="submit" class="btn btn-primary">Upload</button>
          <button type="reset" class="btn">Cancel</button>
        </div>
      </form>
    </div>
    <div class="span6">
      <div class="pull-right">
        <a href="{% url support:admin_index %}">Support Home</a> |
        <a href="{% url support:wine_inventory %}">Wine Inventory</a> |
        <a href="{% url support:view_orders %}">Orders</a>       
      </div>
    </div>
  </div>

  <div class="vertical-space">
    &nbsp;
  </div>

  <div class="row">
    <div class="span12">
      <h2>Current Wine Inventory</h2>
    </div>
    <div class="span12">
      {% render_table wine_inventory %}
    </div>
    <div class="span12">
      <h2>Tasting Kit Inventory</h2>
    </div>
    <div class="span12">
      {% render_table tasting_inventory %}
    </div>
  </div>

  <div class="vertical-space">
    &nbsp;
  </div>

</div>

{% endblock content %}